---

# Installing apache2

- name: Update repo and install apache2
  become: yes
  apt:
    name: apache2
    update_cache: yes
    state: present


- name: Start apache2
  become: yes
  service:
    name: apache2
    state: started
