---


# Playbook to install Jenkins

- name: Installaing java
  hosts: remote
  roles:
    - java
    - jenkins


- name: Installing apache
  hosts: apache
  roles:
    - { role: 'apache', tags: 'apache2'}
